apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
      matchLabels:
          app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name:  postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim  
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        envFrom: 
          - configMapRef:
              name:  postgres-config
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      
        