apiVersion: v1
kind: Service
metadata:
    name: spring-security-app
    labels:
        app: spring-security-app
spec:
    type: NodePort
    ports:
        - port: 8081
          targetPort: 8081
          nodePort: 30285
    selector:
        app: spring-security-app